// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Representantes.Data;

#nullable disable

namespace Representantes.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220520020624_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Representantes.WebApi.Data.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Representantes.WebApi.Data.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<double>("ValorVenda")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensPedidos");
                });

            modelBuilder.Entity("Representantes.WebApi.Data.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RepresentanteId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("RepresentanteId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Representantes.WebApi.Data.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Ração 001",
                            Preco = 100.0
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Medicamento 001",
                            Preco = 89.5
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Equipamento 001",
                            Preco = 500.0
                        },
                        new
                        {
                            Id = 4,
                            Nome = "EPI 001",
                            Preco = 50.0
                        },
                        new
                        {
                            Id = 5,
                            Nome = "EPI 002",
                            Preco = 20.0
                        });
                });

            modelBuilder.Entity("Representantes.WebApi.Data.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Matricula = 100,
                            Nome = "Marcelo",
                            Perfil = 1,
                            Senha = "5e593b53708110fec22c8ebba9b21947b63ff5c382d9df044fd875ca4407c708de3fd805df3c897151976925116d18eaf41a2bd48dad0a2f2ffe31202a882a2e"
                        },
                        new
                        {
                            Id = 2,
                            Matricula = 200,
                            Nome = "Joao",
                            Perfil = 1,
                            Senha = "e4c44ac5c55bb559474d7d9e76507cbfb0b6e4ccd91641ca9ba42bec085e1542cfaa2d4cc64bef239436c9921996e6aa9a93336d6cff01c32c1dc3e8cebe4d9a"
                        },
                        new
                        {
                            Id = 3,
                            Matricula = 300,
                            Nome = "Maria",
                            Perfil = 2,
                            Senha = "e7d7a7f7aeb70e66998a80fd659b476e520d0c9ad1c1aade7c1fa3112df3478efff5906858a80e13da9ce61775f9642e9ec8ebf21bee304d99e68ac242edc6e4"
                        });
                });

            modelBuilder.Entity("Representantes.WebApi.Data.ItemPedido", b =>
                {
                    b.HasOne("Representantes.WebApi.Data.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId");

                    b.HasOne("Representantes.WebApi.Data.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId");

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Representantes.WebApi.Data.Pedido", b =>
                {
                    b.HasOne("Representantes.WebApi.Data.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("Representantes.WebApi.Data.Usuario", "Representante")
                        .WithMany()
                        .HasForeignKey("RepresentanteId");

                    b.Navigation("Cliente");

                    b.Navigation("Representante");
                });
#pragma warning restore 612, 618
        }
    }
}
